// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StanbicAPI.ApiDbContext;

namespace StanbicAPI.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20230112082242_Stanbic")]
    partial class Stanbic
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StanbicAPI.Models.StanbicBankNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvailableAccountBalance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillRefNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessAccountNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessShortCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CallbackUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Msisdn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgAccountBalance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThirdPartyTransId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransAmount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValidateEndPoint")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StanbicBankNotifications");
                });
#pragma warning restore 612, 618
        }
    }
}
